/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 20
   Tile set      : bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BGMap_h_INCLUDE
#define __BGMap_h_INCLUDE

#define BGMapWidth 32
#define BGMapHeight 20
#define BGMapBank 0

extern const unsigned char BGMap[];

#endif

/* End of BGMAP.H */
