/*

 CLOUDBLOCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\demo\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define CloudBlockWidth 4
#define CloudBlockHeight 4
#define CloudBlockBank 0

const unsigned char CloudBlock[] =
{
  0x00,0x00,0x00,0x00,0x01,0x03,0x05,0x06,0x04,0x02,
  0x07,0x08,0x00,0x00,0x00,0x00
};

/* End of CLOUDBLOCK.C */
