/*

 CLOUDBLOCK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\demo\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __CloudBlock_h_INCLUDE
#define __CloudBlock_h_INCLUDE

#define CloudBlockWidth 4
#define CloudBlockHeight 4
#define CloudBlockBank 0

extern const unsigned char CloudBlock[];

#endif

/* End of CLOUDBLOCK.H */
