/*

 EMPTYBLOCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\agame\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define EmptyBlockWidth 4
#define EmptyBlockHeight 4
#define EmptyBlockBank 0

const unsigned char EmptyBlock[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of EMPTYBLOCK.C */
