/*

 FISHBLOCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\demo\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define FishBlockWidth 4
#define FishBlockHeight 4
#define FishBlockBank 0

const unsigned char FishBlock[] =
{
  0x00,0x00,0x00,0x00,0x00,0x1D,0x1F,0x00,0x00,0x1E,
  0x20,0x00,0x00,0x00,0x00,0x00
};

/* End of FISHBLOCK.C */
