/*

 GGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 5
   Tile set      : Z:\usr\src\agame\res\fonts\font_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __GGMap_h_INCLUDE
#define __GGMap_h_INCLUDE

#define GGMapWidth 10
#define GGMapHeight 5
#define GGMapBank 0

extern const unsigned char GGMap[];

#endif

/* End of GGMAP.H */
