/*

 ICEBLOCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\demo\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define IceBlockWidth 4
#define IceBlockHeight 4
#define IceBlockBank 0

const unsigned char IceBlock[] =
{
  0x13,0x15,0x15,0x1A,0x14,0x16,0x18,0x1B,0x14,0x18,
  0x16,0x1B,0x17,0x19,0x19,0x1C
};

/* End of ICEBLOCK.C */
