/*

 SNOWBLOCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\demo\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SnowBlockWidth 4
#define SnowBlockHeight 4
#define SnowBlockBank 0

const unsigned char SnowBlock[] =
{
  0x09,0x0B,0x0B,0x10,0x0A,0x0E,0x0C,0x11,0x0A,0x0C,
  0x0E,0x11,0x0D,0x0F,0x0F,0x12
};

/* End of SNOWBLOCK.C */
