/*

 SNOWBLOCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\agame\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SnowBlockWidth 4
#define SnowBlockHeight 4
#define SnowBlockBank 0

const unsigned char SnowBlock[] =
{
  0x09,0x09,0x09,0x09,0x09,0x09,0x09,0x09,0x0A,0x0A,
  0x0B,0x0A,0x0A,0x0B,0x0A,0x0B
};

/* End of SNOWBLOCK.C */
