/*

 CRACKEDBLOCK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\usr\src\agame\res\bg\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __CrackedBlock_h_INCLUDE
#define __CrackedBlock_h_INCLUDE

#define CrackedBlockWidth 4
#define CrackedBlockHeight 4
#define CrackedBlockBank 0

extern const unsigned char CrackedBlock[];

#endif

/* End of CRACKEDBLOCK.H */
