/*

 SEAMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 10
   Tile set      : Z:\usr\src\agame\res\bg\map\bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __SeaMap_h_INCLUDE
#define __SeaMap_h_INCLUDE

#define SeaMapWidth 32
#define SeaMapHeight 10
#define SeaMapBank 0

extern const unsigned char SeaMap[];

#endif

/* End of SEAMAP.H */
