/*

 MAPTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char MapTiles[] =
{
  0xBF,0x00,0x7F,0x80,0xDB,0x04,0xFD,0x02,
  0xF6,0x01,0x9F,0x40,0xDF,0x20,0xF9,0x04,
  0x00,0x00,0x04,0x00,0x8A,0x00,0x00,0x00,
  0x30,0x00,0x48,0x00,0x00,0x00,0x00,0x00
};

/* End of MAPTILES.C */
