/*

 ICEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __IceMap_h_INCLUDE
#define __IceMap_h_INCLUDE

#define IceMapWidth 32
#define IceMapHeight 32
#define IceMapBank 0

extern const unsigned char IceMap[];

#endif

/* End of ICEMAP.H */
