/*

 MAPTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char MapTiles[] =
{
  0xFF,0x40,0x7F,0x80,0xFB,0x24,0xFD,0x02,
  0xFE,0x09,0xBF,0x60,0xDF,0x20,0xFB,0x06,
  0x00,0xFF,0x04,0xFB,0x8A,0x75,0x00,0xFF,
  0x30,0xCF,0x48,0xB7,0x00,0xFF,0x00,0xFF
};

/* End of MAPTILES.C */
